/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_csc_atd_labworks_text_recogn_NativeInterface */

#ifndef _Included_com_csc_atd_labworks_text_recogn_NativeInterface
#define _Included_com_csc_atd_labworks_text_recogn_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_csc_atd_labworks_text_recogn_NativeInterface
 * Method:    pingLibrary
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_csc_atd_labworks_text_1recogn_NativeInterface_pingLibrary
  (JNIEnv *, jobject);

/*
 * Class:     com_csc_atd_labworks_text_recogn_NativeInterface
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_csc_atd_labworks_text_1recogn_NativeInterface_create
  (JNIEnv *, jobject);

/*
 * Class:     com_csc_atd_labworks_text_recogn_NativeInterface
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_csc_atd_labworks_text_1recogn_NativeInterface_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_csc_atd_labworks_text_recogn_NativeInterface
 * Method:    getBoundingBoxes
 * Signature: (JJ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_csc_atd_labworks_text_1recogn_NativeInterface_getBoundingBoxes
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
